/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.figures.domain.presentation;

import com.unicauca.figures.domain.models.Circle;
import com.unicauca.figures.domain.models.Figure;
import com.unicauca.figures.domain.models.Square;
import com.unicauca.figures.domain.models.Triangle;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class GUIFigures extends javax.swing.JFrame {
    //Atributos
    private Figure figure;
    /**
     * Creates new form GUICircle
     */
    public GUIFigures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbpOpcionesFiguras = new javax.swing.JTabbedPane();
        jPnlCirculo = new javax.swing.JPanel();
        jPnlMenuBotonesCirculo = new javax.swing.JPanel();
        jBtnCalcularCirculo = new javax.swing.JButton();
        jBtnSalirCirculo = new javax.swing.JButton();
        jBtnFormularioCirculo = new javax.swing.JPanel();
        jLblIngreseRadioCirculo = new javax.swing.JLabel();
        jTxtRadioCirculo = new javax.swing.JTextField();
        jLblAreaCirculo = new javax.swing.JLabel();
        jLblPerimetroCirculo = new javax.swing.JLabel();
        jPnlCuadrado = new javax.swing.JPanel();
        jPnlMenuBotonesCuadrado = new javax.swing.JPanel();
        jBtnCalcularCuadrado = new javax.swing.JButton();
        jBtnSalirCuadrado = new javax.swing.JButton();
        jPnlFormularioCuadrado = new javax.swing.JPanel();
        jLblIngreseLadoCuadrado = new javax.swing.JLabel();
        jTxtLadoCuadrado = new javax.swing.JTextField();
        jLblAreaCuadrado = new javax.swing.JLabel();
        jLblPerimetroCuadrado = new javax.swing.JLabel();
        jPnlTriangulo = new javax.swing.JPanel();
        jPnlMenuBotonesTriangulo = new javax.swing.JPanel();
        jBtnCalcularTriangulo = new javax.swing.JButton();
        jBtnSalirTriangulo = new javax.swing.JButton();
        jPnlFormularioTriangulo = new javax.swing.JPanel();
        jLblIngreseBaseTriangulo = new javax.swing.JLabel();
        jTxtBaseTriangulo = new javax.swing.JTextField();
        jLblIngreseAlturaTriangulo = new javax.swing.JLabel();
        jTxtAlturaTriangulo = new javax.swing.JTextField();
        jLblAreaTriangulo = new javax.swing.JLabel();
        jLblPerimetroTriangulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jTbpOpcionesFiguras.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jTbpOpcionesFiguras.setPreferredSize(new java.awt.Dimension(400, 300));

        jPnlCirculo.setLayout(new java.awt.BorderLayout());

        jPnlMenuBotonesCirculo.setLayout(new java.awt.GridLayout(1, 0));

        jBtnCalcularCirculo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jBtnCalcularCirculo.setText("Calcular");
        jBtnCalcularCirculo.setPreferredSize(new java.awt.Dimension(230, 70));
        jBtnCalcularCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularCirculoActionPerformed(evt);
            }
        });
        jPnlMenuBotonesCirculo.add(jBtnCalcularCirculo);

        jBtnSalirCirculo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jBtnSalirCirculo.setText("Salir");
        jBtnSalirCirculo.setPreferredSize(new java.awt.Dimension(230, 70));
        jBtnSalirCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirCirculoActionPerformed(evt);
            }
        });
        jPnlMenuBotonesCirculo.add(jBtnSalirCirculo);

        jPnlCirculo.add(jPnlMenuBotonesCirculo, java.awt.BorderLayout.PAGE_END);

        jBtnFormularioCirculo.setLayout(new java.awt.GridLayout(4, 1));

        jLblIngreseRadioCirculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblIngreseRadioCirculo.setText("Ingrese el radio:");
        jBtnFormularioCirculo.add(jLblIngreseRadioCirculo);

        jTxtRadioCirculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtRadioCirculoKeyTyped(evt);
            }
        });
        jBtnFormularioCirculo.add(jTxtRadioCirculo);

        jLblAreaCirculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblAreaCirculo.setText("Area:");
        jBtnFormularioCirculo.add(jLblAreaCirculo);

        jLblPerimetroCirculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblPerimetroCirculo.setText("Perimetro:");
        jBtnFormularioCirculo.add(jLblPerimetroCirculo);

        jPnlCirculo.add(jBtnFormularioCirculo, java.awt.BorderLayout.CENTER);

        jTbpOpcionesFiguras.addTab("Circulo", jPnlCirculo);

        jPnlCuadrado.setLayout(new java.awt.BorderLayout());

        jPnlMenuBotonesCuadrado.setLayout(new java.awt.GridLayout(1, 2));

        jBtnCalcularCuadrado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jBtnCalcularCuadrado.setText("Calcular");
        jBtnCalcularCuadrado.setPreferredSize(new java.awt.Dimension(230, 70));
        jBtnCalcularCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularCuadradoActionPerformed(evt);
            }
        });
        jPnlMenuBotonesCuadrado.add(jBtnCalcularCuadrado);

        jBtnSalirCuadrado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jBtnSalirCuadrado.setText("Salir");
        jBtnSalirCuadrado.setPreferredSize(new java.awt.Dimension(230, 70));
        jBtnSalirCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirCuadradoActionPerformed(evt);
            }
        });
        jPnlMenuBotonesCuadrado.add(jBtnSalirCuadrado);

        jPnlCuadrado.add(jPnlMenuBotonesCuadrado, java.awt.BorderLayout.PAGE_END);

        jPnlFormularioCuadrado.setLayout(new java.awt.GridLayout(4, 1));

        jLblIngreseLadoCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblIngreseLadoCuadrado.setText("Ingrese el lado:");
        jPnlFormularioCuadrado.add(jLblIngreseLadoCuadrado);

        jTxtLadoCuadrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtLadoCuadradoKeyTyped(evt);
            }
        });
        jPnlFormularioCuadrado.add(jTxtLadoCuadrado);

        jLblAreaCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblAreaCuadrado.setText("Area:");
        jPnlFormularioCuadrado.add(jLblAreaCuadrado);

        jLblPerimetroCuadrado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblPerimetroCuadrado.setText("Perimetro:");
        jPnlFormularioCuadrado.add(jLblPerimetroCuadrado);

        jPnlCuadrado.add(jPnlFormularioCuadrado, java.awt.BorderLayout.CENTER);

        jTbpOpcionesFiguras.addTab("Cuadrado", jPnlCuadrado);

        jPnlTriangulo.setLayout(new java.awt.BorderLayout());

        jPnlMenuBotonesTriangulo.setLayout(new java.awt.GridLayout(1, 2));

        jBtnCalcularTriangulo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jBtnCalcularTriangulo.setText("Calcular");
        jBtnCalcularTriangulo.setPreferredSize(new java.awt.Dimension(230, 70));
        jBtnCalcularTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularTrianguloActionPerformed(evt);
            }
        });
        jPnlMenuBotonesTriangulo.add(jBtnCalcularTriangulo);

        jBtnSalirTriangulo.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jBtnSalirTriangulo.setText("Salir");
        jBtnSalirTriangulo.setPreferredSize(new java.awt.Dimension(230, 70));
        jBtnSalirTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirTrianguloActionPerformed(evt);
            }
        });
        jPnlMenuBotonesTriangulo.add(jBtnSalirTriangulo);

        jPnlTriangulo.add(jPnlMenuBotonesTriangulo, java.awt.BorderLayout.PAGE_END);

        jPnlFormularioTriangulo.setLayout(new java.awt.GridLayout(6, 1));

        jLblIngreseBaseTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblIngreseBaseTriangulo.setText("Ingrese la base:");
        jPnlFormularioTriangulo.add(jLblIngreseBaseTriangulo);

        jTxtBaseTriangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtBaseTrianguloKeyTyped(evt);
            }
        });
        jPnlFormularioTriangulo.add(jTxtBaseTriangulo);

        jLblIngreseAlturaTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblIngreseAlturaTriangulo.setText("Ingrese la altura:");
        jPnlFormularioTriangulo.add(jLblIngreseAlturaTriangulo);

        jTxtAlturaTriangulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtAlturaTrianguloKeyTyped(evt);
            }
        });
        jPnlFormularioTriangulo.add(jTxtAlturaTriangulo);

        jLblAreaTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblAreaTriangulo.setText("Area:");
        jPnlFormularioTriangulo.add(jLblAreaTriangulo);

        jLblPerimetroTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblPerimetroTriangulo.setText("Perimetro:");
        jPnlFormularioTriangulo.add(jLblPerimetroTriangulo);

        jPnlTriangulo.add(jPnlFormularioTriangulo, java.awt.BorderLayout.CENTER);

        jTbpOpcionesFiguras.addTab("Triangulo", jPnlTriangulo);

        getContentPane().add(jTbpOpcionesFiguras, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCalcularCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularCirculoActionPerformed
        // Verificar si el textField está vacío
        if (jTxtRadioCirculo.getText().isEmpty()) {
            // Manejo de errores en caso de que la cadena no pueda ser parseada a double
            JOptionPane.showMessageDialog(null, "Campos vacios, llene los campos para continuar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double radius= 0.0; // Valor por defecto o manejo de error adecuado según tu lógica
        try {
            radius = Double.parseDouble(jTxtRadioCirculo.getText());
        } catch (NumberFormatException e) {
            // Manejo de errores en caso de que la cadena no pueda ser parseada a double
            JOptionPane.showMessageDialog(null, "Error, datos invalidos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        figure = new Circle(radius);
        jLblAreaCirculo.setText("Area: " + figure.calculateArea());
        jLblPerimetroCirculo.setText("Perimetro: " + figure.calculatePerimeter());
    }//GEN-LAST:event_jBtnCalcularCirculoActionPerformed

    private void jTxtRadioCirculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtRadioCirculoKeyTyped
        limitarNumerosYPuntos(evt);
    }//GEN-LAST:event_jTxtRadioCirculoKeyTyped

    private void jBtnSalirCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirCirculoActionPerformed
        System.exit(0); // Cierra la aplicación con código de salida 0
    }//GEN-LAST:event_jBtnSalirCirculoActionPerformed

    private void jBtnCalcularCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularCuadradoActionPerformed
        // Verificar si el textField está vacío
        if (jTxtLadoCuadrado.getText().isEmpty()) {
            // Manejo de errores en caso de que la cadena no pueda ser parseada a double
            JOptionPane.showMessageDialog(null, "Campos vacios, llene los campos para continuar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double lado= 0.0; // Valor por defecto o manejo de error adecuado según tu lógica
        try {
            lado = Double.parseDouble(jTxtLadoCuadrado.getText());
        } catch (NumberFormatException e) {
            // Manejo de errores en caso de que la cadena no pueda ser parseada a double
            JOptionPane.showMessageDialog(null, "Error, datos invalidos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        figure = new Square(lado);
        jLblAreaCuadrado.setText("Area: " + figure.calculateArea());
        jLblPerimetroCuadrado.setText("Perimetro: " + figure.calculatePerimeter()); 
    }//GEN-LAST:event_jBtnCalcularCuadradoActionPerformed

    private void jBtnSalirCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirCuadradoActionPerformed
        System.exit(0); // Cierra la aplicación con código de salida 0
    }//GEN-LAST:event_jBtnSalirCuadradoActionPerformed

    private void jTxtLadoCuadradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLadoCuadradoKeyTyped
        limitarNumerosYPuntos(evt);
    }//GEN-LAST:event_jTxtLadoCuadradoKeyTyped

    private void jBtnCalcularTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularTrianguloActionPerformed
        // Verificar si el textField está vacío
        if (jTxtBaseTriangulo.getText().isEmpty() || jTxtAlturaTriangulo.getText().isEmpty()) {
            // Manejo de errores en caso de que la cadena no pueda ser parseada a double
            JOptionPane.showMessageDialog(null, "Campos vacios, llene los campos para continuar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double base= 0.0; // Valor por defecto o manejo de error adecuado según tu lógica
        double altura= 0.0; // Valor por defecto o manejo de error adecuado según tu lógica
        try {
            base = Double.parseDouble(jTxtBaseTriangulo.getText());
            altura = Double.parseDouble(jTxtAlturaTriangulo.getText());
        } catch (NumberFormatException e) {
            // Manejo de errores en caso de que la cadena no pueda ser parseada a double
            JOptionPane.showMessageDialog(null, "Error, datos invalidos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        figure = new Triangle(base,altura);
        jLblAreaTriangulo.setText("Area: " + figure.calculateArea());
        jLblPerimetroTriangulo.setText("Perimetro: " + figure.calculatePerimeter());
    }//GEN-LAST:event_jBtnCalcularTrianguloActionPerformed

    private void jBtnSalirTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirTrianguloActionPerformed
        System.exit(0); // Cierra la aplicación con código de salida 0
    }//GEN-LAST:event_jBtnSalirTrianguloActionPerformed

    private void jTxtBaseTrianguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBaseTrianguloKeyTyped
        limitarNumerosYPuntos(evt);
    }//GEN-LAST:event_jTxtBaseTrianguloKeyTyped

    private void jTxtAlturaTrianguloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtAlturaTrianguloKeyTyped
        limitarNumerosYPuntos(evt);
    }//GEN-LAST:event_jTxtAlturaTrianguloKeyTyped

    public void limitarNumerosYPuntos(KeyEvent e) {
        char c = e.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            e.consume(); // Ignorar el carácter no válido
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalcularCirculo;
    private javax.swing.JButton jBtnCalcularCuadrado;
    private javax.swing.JButton jBtnCalcularTriangulo;
    private javax.swing.JPanel jBtnFormularioCirculo;
    private javax.swing.JButton jBtnSalirCirculo;
    private javax.swing.JButton jBtnSalirCuadrado;
    private javax.swing.JButton jBtnSalirTriangulo;
    private javax.swing.JLabel jLblAreaCirculo;
    private javax.swing.JLabel jLblAreaCuadrado;
    private javax.swing.JLabel jLblAreaTriangulo;
    private javax.swing.JLabel jLblIngreseAlturaTriangulo;
    private javax.swing.JLabel jLblIngreseBaseTriangulo;
    private javax.swing.JLabel jLblIngreseLadoCuadrado;
    private javax.swing.JLabel jLblIngreseRadioCirculo;
    private javax.swing.JLabel jLblPerimetroCirculo;
    private javax.swing.JLabel jLblPerimetroCuadrado;
    private javax.swing.JLabel jLblPerimetroTriangulo;
    private javax.swing.JPanel jPnlCirculo;
    private javax.swing.JPanel jPnlCuadrado;
    private javax.swing.JPanel jPnlFormularioCuadrado;
    private javax.swing.JPanel jPnlFormularioTriangulo;
    private javax.swing.JPanel jPnlMenuBotonesCirculo;
    private javax.swing.JPanel jPnlMenuBotonesCuadrado;
    private javax.swing.JPanel jPnlMenuBotonesTriangulo;
    private javax.swing.JPanel jPnlTriangulo;
    private javax.swing.JTabbedPane jTbpOpcionesFiguras;
    private javax.swing.JTextField jTxtAlturaTriangulo;
    private javax.swing.JTextField jTxtBaseTriangulo;
    private javax.swing.JTextField jTxtLadoCuadrado;
    private javax.swing.JTextField jTxtRadioCirculo;
    // End of variables declaration//GEN-END:variables
}
